name: Emotion-detection CI pipeline

on: push

jobs:
  run-dvc-pipeline:
  
    runs-on: ubuntu-latest
    steps:
      - name: chekcout code 
        uses: actions/checkout@v3
      - name: setup enviornment 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install dependancy
        run: |
          pip install requiremenets.txt
      - name: run pipeline
        run: |
          dvc repro