name: Emotion-detection CI pipeline

on: push

jobs:
  run-dvc-pipeline:
  
    runs-on: ubuntu-latest
    steps:
      - name: chekcout code 
        uses: actions/checkout@v3
      - name: setup enviornment 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependancy
        run: |
          pip install -r requirements.txt
      - name: run pipeline
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }} #this is the flow where in github action it will take the dagshub token from my github secret and use it when is is required. crearte a dagshub token and add it into github secrets and varaible so that you can use it anytime through this code   
        run: |
          dvc repro

      - name: run model test
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py 