name: Emotion-detection CI pipeline

on: push

jobs:
  run-dvc-pipeline:
  
    runs-on: ubuntu-latest
    steps:
      - name: chekcout code 
        uses: actions/checkout@v3
      - name: setup enviornment 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependancy
        run: |
          pip install -r requirements.txt
      - name: run pipeline
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }} #this is the flow where in github action it will take the dagshub token from my github secret and use it when is is required. crearte a dagshub token and add it into github secrets and varaible so that you can use it anytime through this code   
        run: |
          dvc repro

      - name: run model test
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py 

      - name: promote model production
        if: success()
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python scripts/promote_model.py

      - name: run test for flask app 
        if: success()
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_flask_app.py

      - name: Login to AWS ECR
        if: success()
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 001956664770.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        if: success()
        run: |
          docker build -t sumit_emotion_detection .

      - name: Tag Docker image
        if: success()
        run: |
          docker tag sumit_emotion_detection:latest 001956664770.dkr.ecr.eu-north-1.amazonaws.com/sumit_emotion_detection:latest

      - name: Push Docker image to AWS ECR
        if: success()
        run: |
          docker push 001956664770.dkr.ecr.eu-north-1.amazonaws.com/sumit_emotion_detection:latest